### ISSUE TITLE
Code does not work with latest ionic

### ISSUE THREAD

**Issue by gigocabrera** [srinivastamada/ionic2-camera#1]
Hi @srinivastamada, first of all thank you very much for sharing. I watched your video in youtube and that's how I landed here.

I'm having problems with your sample code and I was wondering if you can help. After taking a photo or several photos all I see is blank images in the grid. I don't see the photos. The only difference is that in my environment I'm already running CLI v3 and ionic 3.2.1.

Not sure if the camera plugin stopped working after the upgrade. Does it work for you with CLI v3 and ionic 3.2.1?

IONIC INFO
```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.3.1
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.1
    ios-sim    : 4.1.1```

**Comment by srinivastamada** [comment]
How you deployed the app, ionic view  doesn't support native features. Deploy with Xcode 

Thanks

Srinivas Tamada

**Comment by gigocabrera** [comment]
That was it. I was using ionic view to test it but once I deployed to device with xcode it worked. Thank you very much!!!
